Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,10 +22,12 @@ jobs:
         shell: bash
 
       - name: Test SSH Connection
-        run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH Connection Successful'"
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH Connection Successful'"
 
       - name: Check and Install Node.js and npm if needed
-        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
+        run: |
+          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
           if ! command -v node &> /dev/null || ! command -v npm &> /dev/null; then
             echo 'Node.js or npm not found. Installing...'
             curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
@@ -33,20 +35,22 @@ jobs:
           else
             echo 'Node.js and npm are already installed.'
           fi
-        "
+          EOF
 
       - name: Check Node.js and npm versions
-        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "node -v && npm -v"
+        run: |
+          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "node -v && npm -v"
 
       - name: Check and Install PM2 if needed
-        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
+        run: |
+          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
           if ! command -v pm2 &> /dev/null; then
             echo 'PM2 not found. Installing...'
             npm install -g pm2
           else
             echo 'PM2 is already installed.'
           fi
-        "
+          EOF
 
       - name: Deploy to server
         env:
@@ -56,50 +60,50 @@ jobs:
           PORT: ${{ secrets.PORT }}
           G_TOKEN: ${{ secrets.G_TOKEN }}
         run: |
-          ssh -o StrictHostKeyChecking=no $USER@$HOST "
-            sudo mkdir -p $APP_DIR
-            sudo chown -R \$USER:\$USER $APP_DIR
+          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
+          sudo mkdir -p $APP_DIR
+          sudo chown -R $USER:$USER $APP_DIR
 
-            if [ ! -d $APP_DIR/.git ]; then
-              git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
-            else 
-              cd $APP_DIR
-              git pull https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git main
-            fi
-
+          if [ ! -d $APP_DIR/.git ]; then
+            git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
+          else 
             cd $APP_DIR
+            git pull https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git main
+          fi
 
-            echo 'PORT=${PORT}
-            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-            DB_NAME=${{ secrets.DB_NAME }}
-            JWT_SECRET=${{ secrets.JWT_SECRET }}
-            JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}
-            BASE_URL=${{ secrets.BASE_URL }}
-            FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
-            FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
-            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
-            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
-            GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
-            FACEBOOK_CALLBACK_URL=${{ secrets.FACEBOOK_CALLBACK_URL }}
-            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
-            LINKEDIN_ID=${{ secrets.LINKEDIN_ID }}
-            LINKEDIN_SECRET=${{ secrets.LINKEDIN_SECRET }}
-            LINKEDIN_CALLBACK_URL=${{ secrets.LINKEDIN_CALLBACK_URL }}
-            YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }}
-            YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }}
-            YANDEX_CALLBACK_URL=${{ secrets.YANDEX_CALLBACK_URL }}' > .env
+          cd $APP_DIR
 
-            npm install
-            npm run build
+          echo 'PORT=${PORT}
+          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
+          DB_NAME=${{ secrets.DB_NAME }}
+          JWT_SECRET=${{ secrets.JWT_SECRET }}
+          JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}
+          BASE_URL=${{ secrets.BASE_URL }}
+          FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
+          FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
+          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
+          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
+          GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
+          FACEBOOK_CALLBACK_URL=${{ secrets.FACEBOOK_CALLBACK_URL }}
+          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
+          LINKEDIN_ID=${{ secrets.LINKEDIN_ID }}
+          LINKEDIN_SECRET=${{ secrets.LINKEDIN_SECRET }}
+          LINKEDIN_CALLBACK_URL=${{ secrets.LINKEDIN_CALLBACK_URL }}
+          YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }}
+          YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }}
+          YANDEX_CALLBACK_URL=${{ secrets.YANDEX_CALLBACK_URL }}' > .env
 
-            if ! command -v pm2 &> /dev/null; then
-              echo 'PM2 not found. Installing...'
-              npm install -g pm2
-            fi
+          npm install
+          npm run build
 
-            pm2 delete sector_tech || true
-            pm2 start dist/index.js --name sector_tech
-          "
+          if ! command -v pm2 &> /dev/null; then
+            echo 'PM2 not found. Installing...'
+            npm install -g pm2
+          fi
+
+          pm2 delete sector_tech || true
+          pm2 start dist/index.js --name sector_tech
+          EOF
         shell: bash
 
       - name: Check PM2 Status
