Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,21 +19,15 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           eval "$(ssh-agent -s)"
           ssh-add ~/.ssh/id_rsa
+          ssh-keygen -F ${{ secrets.HOST }} || ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
         shell: bash
-
-      - name: Debug Secrets Values
-        run: |
-          echo "HOST=${{ secrets.HOST }}"
-          echo "USERNAME=${{ secrets.USERNAME }}"
-          echo "APP_DIR=/root/sector_technology/sector-tech-backend"
 
       - name: Deploy to server
         run: |
-          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
-          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
+          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
           set -e
 
-          # Define variables explicitly within SSH session
+          # Define variables
           USERNAME="${{ secrets.USERNAME }}"
           HOST="${{ secrets.HOST }}"
           APP_DIR="/root/sector_technology/sector-tech-backend"
@@ -53,8 +47,8 @@ jobs:
             git clone https://${{ secrets.G_TOKEN }}@github.com/boburDev/sector-tech-backend.git $APP_DIR
           else
             cd $APP_DIR
-            git reset --hard HEAD
-            git pull origin main
+            git fetch --all
+            git reset --hard origin/main
           fi
 
           cd $APP_DIR
@@ -81,15 +75,24 @@ jobs:
           YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }}
           YANDEX_CALLBACK_URL=${{ secrets.YANDEX_CALLBACK_URL }}
           EOL
+          
+          chmod 600 .env
 
-          echo "Restarting PM2 process..."
+          echo "Checking if PM2 is installed..."
+          if ! command -v pm2 &> /dev/null; then
+            echo "PM2 not found, installing..."
+            npm install -g pm2
+          fi
+
+          echo "Checking if PM2 process exists..."
           if pm2 list | grep -q sector_tech; then
             echo "PM2 process found. Restarting..."
             pm2 restart sector_tech            
-          fi
+          else
             echo "PM2 process not found. Starting a new one..."
             npm install
             npm run build
             pm2 start dist/index.js --name sector_tech
+          fi
           '
         shell: bash
